### ISSUE TITLE
As a developer, I want to understand why Artemis 2.35 is not working properly and fix it

### ISSUE THREAD

**Issue by ArvinEsmailzadeh-NOAA** [NOAA-OWP/wres#69]
If I use Artemis 2.34, the service appears to run properly: I can bring it up, post smoke tests, and see successes. If I use 2.35, subscribers fail to negotiate; example exception summary:

```
2024-06-25T13:43:45.936+0000 ERROR EvaluationStatusTracker While tracking evaluation 9uGAGVwNp0RbPcbkbk-ETiB8p-4, encountered an error in a messaging client that prevented the evaluation from succeeding. The error message is:
client_id: "CODjKPSqSD14nQy37vqUdAe_sL0"
time {
seconds: 1719323025
nanos: 931731891
}
completion_status: EVALUATION_COMPLETE_REPORTED_FAILURE
status_events {
status_level: ERROR
event_message: "class wres.events.subscribe.SubscriberTimedOutException: Failed to negotiate all subscriptions within the timeout period of PT5M. Subscribers could not be negotiated for the following output formats: [CSV2]"
}
```

This ticket can be resolved once we have identified the issue and fixed it,

**Comment by james-d-brown** [comment]
Version 2.36 is available now. I would try that and, assuming it still fails, I would check and clean-up any explicit dependency overrides in the `build.gradle` for transitive dependencies that formerly had CVEs but have probably since been updated. You will see these overrides nearby/underneath the main dependency. Forcibly swapping these transitive dependencies can sometimes lead to problems when the main dependency is upgraded.

**Comment by james-d-brown** [comment]
Dependency has a new version, 2.36. Goal is to update to this, which is also failing for the same reason as 2.35.

**Comment by james-d-brown** [comment]
Issue appears to be with messages not being routed to queues at all. So not a superficial issue, but not necessarily a hard issue to fix. Looking at the broker monitor...

**Comment by james-d-brown** [comment]
Broker monitor indicates messages being sent, but not enqueued for consumption.

**Comment by james-d-brown** [comment]
Noticed a discrepancy between the queue address as seen by producers and consumers and sort of stumbled across what appears to be the fix. After 2.35, when creating topics from a binding url, the declaration of parameters appears to result in messages not being routed to queues properly. Not exactly sure why.

In other words, rather than this:

`topic.evaluation = BURL:topic://amq.topic/evaluation?routingkey='evaluation'&exclusive='false'&autodelete='true'`

This:

`topic.evaluation = BURL:topic://amq.topic/evaluation`

Seems to work.

I think those parameters are legacy anyway, Certainly, the `routingKey` is a hangover from amqp 0.9.1 topics.
